import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import Product from '../models/product';
import { generateUUID } from '../utils/uuid';
import { categories } from './category.service';
import Page, { createPage } from '../models/page';
import Pageable from '../models/pageable';

export const products: Product[] = [
  // Prescription Drugs (8)
  {
    id: generateUUID,
    health_registration_number: 'NDC12345-6789',
    product_name: 'Lisinopril 10mg Tablets',
    cost_price: 4.5,
    sale_price: 12.99,
    admision_date: new Date('2024-01-15'),
    expiration_date: new Date('2026-01-14'),
    supplier_name: 'Pfizer Inc.',
    require: 'Prescription',
    brand_name: 'Prinivil',
    description: 'ACE inhibitor for hypertension',
    composition: 'Lisinopril 10mg',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC54321-9876',
    product_name: 'Atorvastatin 20mg Tablets',
    cost_price: 5.0,
    sale_price: 14.99,
    admision_date: new Date('2024-02-10'),
    expiration_date: new Date('2026-02-09'),
    supplier_name: 'Merck & Co.',
    require: 'Prescription',
    brand_name: 'Lipitor',
    description: 'Statin for cholesterol management',
    composition: 'Atorvastatin 20mg',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC11111-2222',
    product_name: 'Metformin 500mg Tablets',
    cost_price: 3.75,
    sale_price: 10.99,
    admision_date: new Date('2024-03-05'),
    expiration_date: new Date('2026-03-04'),
    supplier_name: 'Novartis Pharmaceuticals',
    require: 'Prescription',
    brand_name: 'Glucophage',
    description: 'Oral antihyperglycemic agent',
    composition: 'Metformin HCl 500mg',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC33333-4444',
    product_name: 'Omeprazole 20mg Capsules',
    cost_price: 4.0,
    sale_price: 11.99,
    admision_date: new Date('2024-01-20'),
    expiration_date: new Date('2026-01-19'),
    supplier_name: 'AstraZeneca',
    require: 'Prescription',
    brand_name: 'Prilosec',
    description: 'Proton pump inhibitor for GERD',
    composition: 'Omeprazole 20mg',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC55555-6666',
    product_name: 'Albuterol Inhaler 90mcg',
    cost_price: 20.0,
    sale_price: 45.0,
    admision_date: new Date('2024-04-01'),
    expiration_date: new Date('2025-12-31'),
    supplier_name: 'Teva Pharmaceuticals',
    require: 'Prescription',
    brand_name: 'Ventolin',
    description: 'Bronchodilator for asthma',
    composition: 'Albuterol sulfate 90mcg/actuation',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC77777-8888',
    product_name: 'Sertraline 50mg Tablets',
    cost_price: 6.0,
    sale_price: 15.99,
    admision_date: new Date('2024-02-25'),
    expiration_date: new Date('2026-02-24'),
    supplier_name: 'Pfizer Inc.',
    require: 'Prescription',
    brand_name: 'Zoloft',
    description: 'SSRI antidepressant',
    composition: 'Sertraline HCl 50mg',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC99999-0000',
    product_name: 'Levothyroxine 50mcg Tablets',
    cost_price: 2.5,
    sale_price: 9.99,
    admision_date: new Date('2024-03-15'),
    expiration_date: new Date('2026-03-14'),
    supplier_name: 'AbbVie',
    require: 'Prescription',
    brand_name: 'Synthroid',
    description: 'Thyroid hormone replacement',
    composition: 'Levothyroxine sodium 50mcg',
    category: categories[0]
  },
  {
    id: generateUUID,
    health_registration_number: 'NDC10101-2020',
    product_name: 'Amoxicillin 500mg Capsules',
    cost_price: 3.0,
    sale_price: 12.49,
    admision_date: new Date('2024-04-10'),
    expiration_date: new Date('2026-04-09'),
    supplier_name: 'GlaxoSmithKline',
    require: 'Prescription',
    brand_name: 'Amoxil',
    description: 'Antibiotic for bacterial infections',
    composition: 'Amoxicillin trihydrate 500mg',
    category: categories[0]
  },

  // Over-the-Counter (OTC) (8)
  {
    id: generateUUID,
    health_registration_number: 'OTC0001',
    product_name: 'Ibuprofen 200mg Tablets',
    cost_price: 2.0,
    sale_price: 7.99,
    admision_date: new Date('2024-01-05'),
    expiration_date: new Date('2026-01-04'),
    supplier_name: 'Johnson & Johnson',
    require: 'OTC',
    brand_name: 'Advil',
    description: 'Nonsteroidal anti-inflammatory pain reliever',
    composition: 'Ibuprofen 200mg',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0002',
    product_name: 'Acetaminophen 500mg Tablets',
    cost_price: 1.5,
    sale_price: 6.49,
    admision_date: new Date('2024-02-12'),
    expiration_date: new Date('2026-02-11'),
    supplier_name: 'McNeil Consumer Healthcare',
    require: 'OTC',
    brand_name: 'Tylenol',
    description: 'Pain reliever and fever reducer',
    composition: 'Acetaminophen 500mg',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0003',
    product_name: 'Diphenhydramine 25mg Capsules',
    cost_price: 2.5,
    sale_price: 8.99,
    admision_date: new Date('2024-03-08'),
    expiration_date: new Date('2026-03-07'),
    supplier_name: 'Bayer HealthCare',
    require: 'OTC',
    brand_name: 'Benadryl',
    description: 'Allergy relief antihistamine',
    composition: 'Diphenhydramine HCl 25mg',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0004',
    product_name: 'Loratadine 10mg Tablets',
    cost_price: 3.0,
    sale_price: 9.49,
    admision_date: new Date('2024-01-22'),
    expiration_date: new Date('2026-01-21'),
    supplier_name: 'Pfizer Consumer Healthcare',
    require: 'OTC',
    brand_name: 'Claritin',
    description: 'Non-drowsy antihistamine for allergy relief',
    composition: 'Loratadine 10mg',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0005',
    product_name: 'Guaifenesin 100mg/5mL Syrup',
    cost_price: 4.0,
    sale_price: 11.99,
    admision_date: new Date('2024-04-02'),
    expiration_date: new Date('2025-12-01'),
    supplier_name: 'Reckitt Benckiser',
    require: 'OTC',
    brand_name: 'Mucinex',
    description: 'Expectorant for cough relief',
    composition: 'Guaifenesin 100mg/5mL',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0006',
    product_name: 'Calamine Lotion 8%',
    cost_price: 1.0,
    sale_price: 5.99,
    admision_date: new Date('2024-02-18'),
    expiration_date: new Date('2026-02-17'),
    supplier_name: 'Chlor-Med Pharmaceuticals',
    require: 'OTC',
    description: 'Soothing lotion for skin irritation',
    composition: 'Calamine 8%',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0007',
    product_name: 'Bismuth Subsalicylate 262mg Tablets',
    cost_price: 2.0,
    sale_price: 7.49,
    admision_date: new Date('2024-03-20'),
    expiration_date: new Date('2026-03-19'),
    supplier_name: 'Procter & Gamble',
    require: 'OTC',
    brand_name: 'Pepto-Bismol',
    description: 'Relieves upset stomach and diarrhea',
    composition: 'Bismuth subsalicylate 262mg',
    category: categories[1]
  },
  {
    id: generateUUID,
    health_registration_number: 'OTC0008',
    product_name: 'Pseudoephedrine 30mg Tablets',
    cost_price: 3.5,
    sale_price: 10.99,
    admision_date: new Date('2024-04-15'),
    expiration_date: new Date('2026-04-14'),
    supplier_name: 'Johnson & Johnson',
    require: 'OTC',
    brand_name: 'Sudafed',
    description: 'Nasal decongestant for sinus relief',
    composition: 'Pseudoephedrine HCl 30mg',
    category: categories[1]
  },

  // Vitamins & Supplements (8)
  {
    id: generateUUID,
    health_registration_number: 'SUPP0001',
    product_name: 'Vitamin C 1000mg Tablets',
    cost_price: 4.0,
    sale_price: 14.99,
    admision_date: new Date('2024-01-11'),
    expiration_date: new Date('2026-01-10'),
    supplier_name: 'Nature Made',
    require: 'OTC',
    description: 'Immune system support',
    composition: 'Ascorbic Acid 1000mg',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0002',
    product_name: 'Vitamin D3 2000 IU Softgels',
    cost_price: 5.0,
    sale_price: 16.99,
    admision_date: new Date('2024-02-14'),
    expiration_date: new Date('2026-02-13'),
    supplier_name: 'Carlson Labs',
    require: 'OTC',
    description: 'Bone and immune health support',
    composition: 'Cholecalciferol (Vitamin D3) 2000 IU',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0003',
    product_name: 'Fish Oil 1000mg Gel Capsules',
    cost_price: 6.0,
    sale_price: 18.99,
    admision_date: new Date('2024-03-01'),
    expiration_date: new Date('2026-02-28'),
    supplier_name: 'Nordic Naturals',
    require: 'OTC',
    description: 'Supports heart health',
    composition: 'Omega-3 Fatty Acids 1000mg',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0004',
    product_name: 'Calcium 600mg + D3 400 IU Tablets',
    cost_price: 5.5,
    sale_price: 17.49,
    admision_date: new Date('2024-01-29'),
    expiration_date: new Date('2026-01-28'),
    supplier_name: 'Kirkland Signature',
    require: 'OTC',
    description: 'Bone strength support',
    composition: 'Calcium Carbonate 600mg, Vitamin D3 400 IU',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0005',
    product_name: 'Probiotic 10 Billion CFU Capsules',
    cost_price: 7.0,
    sale_price: 19.99,
    admision_date: new Date('2024-02-05'),
    expiration_date: new Date('2026-02-04'),
    supplier_name: 'Garden of Life',
    require: 'OTC',
    description: 'Digestive and immune support',
    composition: 'Blend of probiotic strains, 10B CFU',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0006',
    product_name: 'Magnesium 400mg Tablets',
    cost_price: 4.5,
    sale_price: 15.49,
    admision_date: new Date('2024-03-18'),
    expiration_date: new Date('2026-03-17'),
    supplier_name: 'Now Foods',
    require: 'OTC',
    description: 'Muscle and nerve function support',
    composition: 'Magnesium Oxide 400mg',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0007',
    product_name: 'Biotin 5000mcg Tablets',
    cost_price: 3.5,
    sale_price: 13.99,
    admision_date: new Date('2024-04-06'),
    expiration_date: new Date('2026-04-05'),
    supplier_name: 'Sports Research',
    require: 'OTC',
    description: 'Hair, skin, and nail support',
    composition: 'Biotin 5000mcg',
    category: categories[2]
  },
  {
    id: generateUUID,
    health_registration_number: 'SUPP0008',
    product_name: 'Zinc 50mg Tablets',
    cost_price: 2.5,
    sale_price: 12.49,
    admision_date: new Date('2024-02-20'),
    expiration_date: new Date('2026-02-19'),
    supplier_name: `Nature's Bounty`,
    require: 'OTC',
    description: 'Immune system support',
    composition: 'Zinc Gluconate 50mg',
    category: categories[2]
  },

  // Medical Devices (8)
  {
    id: generateUUID,
    health_registration_number: 'MD0001',
    product_name: 'Digital Thermometer',
    cost_price: 8.0,
    sale_price: 24.99,
    admision_date: new Date('2024-01-18'),
    expiration_date: new Date('2030-01-17'),
    supplier_name: 'Omron Healthcare',
    require: 'OTC',
    description: 'Digital oral thermometer',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0002',
    product_name: 'Blood Pressure Monitor',
    cost_price: 25.0,
    sale_price: 59.99,
    admision_date: new Date('2024-02-22'),
    expiration_date: new Date('2030-02-21'),
    supplier_name: 'Beurer',
    require: 'OTC',
    description: 'Automatic upper arm blood pressure monitor',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0003',
    product_name: 'Glucometer Kit',
    cost_price: 15.0,
    sale_price: 39.99,
    admision_date: new Date('2024-03-12'),
    expiration_date: new Date('2030-03-11'),
    supplier_name: 'Accu-Chek',
    require: 'OTC',
    description: 'Blood glucose monitoring kit',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0004',
    product_name: 'Pulse Oximeter',
    cost_price: 12.0,
    sale_price: 34.99,
    admision_date: new Date('2024-01-30'),
    expiration_date: new Date('2030-01-29'),
    supplier_name: 'Contec',
    require: 'OTC',
    description: 'Finger pulse oxygen saturation monitor',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0005',
    product_name: 'Nebulizer Machine',
    cost_price: 30.0,
    sale_price: 79.99,
    admision_date: new Date('2024-04-03'),
    expiration_date: new Date('2030-04-02'),
    supplier_name: 'Philips Respironics',
    require: 'Prescription',
    description: 'Home ultrasonic nebulizer for respiratory therapy',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0006',
    product_name: 'Wheelchair',
    cost_price: 85.0,
    sale_price: 199.99,
    admision_date: new Date('2024-02-28'),
    expiration_date: new Date('2030-02-27'),
    supplier_name: 'Drive Medical',
    require: 'Prescription',
    description: 'Folding wheelchair with aluminum frame',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0007',
    product_name: 'Crutches, Adjustable',
    cost_price: 10.0,
    sale_price: 29.99,
    admision_date: new Date('2024-03-25'),
    expiration_date: new Date('2030-03-24'),
    supplier_name: 'Mueller Sports Medicine',
    require: 'Prescription',
    description: 'Adjustable aluminum forearm crutches',
    category: categories[3]
  },
  {
    id: generateUUID,
    health_registration_number: 'MD0008',
    product_name: 'Blood Glucose Test Strips (50)',
    cost_price: 8.0,
    sale_price: 22.99,
    admision_date: new Date('2024-01-27'),
    expiration_date: new Date('2026-01-26'),
    supplier_name: 'OneTouch',
    require: 'OTC',
    description: 'Test strips for OneTouch glucometer',
    composition: 'Glucose test strip',
    category: categories[3]
  },

  // Personal Care (8)
  {
    id: generateUUID,
    health_registration_number: 'PC0001',
    product_name: 'Hand Sanitizer 8oz',
    cost_price: 2.0,
    sale_price: 5.99,
    admision_date: new Date('2024-01-07'),
    expiration_date: new Date('2026-01-06'),
    supplier_name: 'Purell',
    require: 'OTC',
    description: 'Alcohol-based hand sanitizer',
    composition: 'Ethyl alcohol 70%',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0002',
    product_name: 'Antiseptic Wipes (100)',
    cost_price: 3.0,
    sale_price: 9.49,
    admision_date: new Date('2024-02-16'),
    expiration_date: new Date('2026-02-15'),
    supplier_name: 'Medline Industries',
    require: 'OTC',
    description: 'Sterile antiseptic wipes',
    composition: 'Isopropyl alcohol 70%',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0003',
    product_name: 'Reusable Face Mask',
    cost_price: 4.5,
    sale_price: 12.99,
    admision_date: new Date('2024-03-03'),
    expiration_date: new Date('2030-03-02'),
    supplier_name: '3M',
    require: 'OTC',
    description: 'Washable cloth face mask',
    composition: 'Polyester/cotton blend',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0004',
    product_name: 'First Aid Kit (50 pieces)',
    cost_price: 10.0,
    sale_price: 24.99,
    admision_date: new Date('2024-01-25'),
    expiration_date: new Date('2030-01-24'),
    supplier_name: 'Johnson & Johnson',
    require: 'OTC',
    description: 'Complete first aid kit for home use',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0005',
    product_name: 'Moisturizing Lotion 16oz',
    cost_price: 3.5,
    sale_price: 11.49,
    admision_date: new Date('2024-02-08'),
    expiration_date: new Date('2026-02-07'),
    supplier_name: 'Aveeno',
    require: 'OTC',
    description: 'Fragrance-free moisturizing lotion',
    composition: 'Colloidal oatmeal',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0006',
    product_name: 'Alcohol Prep Pads (100)',
    cost_price: 2.5,
    sale_price: 7.99,
    admision_date: new Date('2024-03-14'),
    expiration_date: new Date('2026-03-13'),
    supplier_name: 'Dynarex',
    require: 'OTC',
    description: 'Sterile alcohol prep pads',
    composition: 'Isopropyl alcohol 70%',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0007',
    product_name: 'Sunscreen SPF 30 Lotion',
    cost_price: 4.0,
    sale_price: 13.99,
    admision_date: new Date('2024-04-12'),
    expiration_date: new Date('2026-04-11'),
    supplier_name: 'Neutrogena',
    require: 'OTC',
    description: 'Broad spectrum UVA/UVB protection',
    composition: 'Avobenzone 3%, Homosalate 10%',
    category: categories[4]
  },
  {
    id: generateUUID,
    health_registration_number: 'PC0008',
    product_name: 'ChapStick Lip Balm',
    cost_price: 1.0,
    sale_price: 4.99,
    admision_date: new Date('2024-02-28'),
    expiration_date: new Date('2026-02-27'),
    supplier_name: 'The Mentholatum Company',
    require: 'OTC',
    description: 'Moisturizing lip balm',
    composition: 'Petrolatum, beeswax, menthol',
    category: categories[4]
  }
];


@Injectable({
  providedIn: 'root'
})
export class ProductService {

  getProducts({ size = 10, page = 1 }: Pageable){
    return of(createPage(products, { size, page }));
  }
}
